# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - demo
    tags:
      - v*

permissions: write-all

env:
  BUILDKIT_NO_CLIENT_TOKEN: 1 # docker buildkit env
  # gitea action download node.js skip certificate !https
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  build_images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-22.04  # Uncomment it if you use it on Gitea

    strategy:
      fail-fast: true
      matrix:
        target:
          - name: Build and Push Images (Latest / Release)
            tag: ghcr.io/yaominlouis/${{ github.event.repository.name }}

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker context for buildx
        run: |
          docker context create builders || docker context use builders

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Set image tags
        id: set-tags
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "MAIN_TAG=${TAG_NAME}" >> $GITHUB_OUTPUT
          else
            echo "MAIN_TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Move to demo folder
        run: |
          cd ./demo

      - name: ${{ matrix.target.name }}
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./demo
          file: ./Dockerfile
          labels: ${{ github.sha }}
          tags: |
            ${{ matrix.target.tag }}:${{ steps.set-tags.outputs.MAIN_TAG }}
            ${{ matrix.target.tag }}:${{ github.sha }}
          sbom: false
          provenance: false
          cache-from: type=registry,ref=${{ matrix.target.tag }}:buildcache
          cache-to: type=registry,ref=${{ matrix.target.tag }}:buildcache,image-manifest=true,oci-mediatypes=true,mode=max
